import http from 'http'; import fs from 'fs'; import path from 'path'; import crypto from 'crypto'; import {URL} from 'url';
const PORT=Number(process.env.PORT||3000), BASE=process.env.PUBLIC_BASE_URL||`http://localhost:${PORT}`, DB=path.resolve('data/db.json'), PUB=path.resolve('public');
const seed={products:[['Oud Stallion',175000,3],['Bianco Latte',150000,5],['Babycat',180000,2],['Baccarat Rouge',210000,0],['Oud Wood',160000,4]].map((x,i)=>({id:`P${i+1}`,name:x[0],size:'50 ml',price:x[1],stock:x[2]})),customers:[],orders:[],events:[]};
function load(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return structuredClone(seed)}} function save(d){fs.mkdirSync(path.dirname(DB),{recursive:true});fs.writeFileSync(DB,JSON.stringify(d,null,2))} if(!fs.existsSync(DB))save(seed);
const send=(r,s,b,t='application/json')=>{r.writeHead(s,{'content-type':t});r.end(t.includes('json')?JSON.stringify(b):b)}, oid=()=>`MM${Date.now().toString().slice(-8)}`, find=(d,id)=>d.products.find(p=>p.id===id);
async function body(req){let a='';for await(const c of req)a+=c;return a?JSON.parse(a):{}} function reserve(d,items){for(const i of items){const p=find(d,i.product_id);if(!p||!Number.isInteger(i.qty)||i.qty<1||p.stock<i.qty)throw Error(`Stock insuffisant: ${p?.name||i.product_id}`)}for(const i of items)find(d,i.product_id).stock-=i.qty} function restore(d,o){if(o.stock_reserved){for(const i of o.items){const p=find(d,i.product_id);if(p)p.stock+=i.qty}o.stock_reserved=false}}
async function wave(o){if(!process.env.WAVE_API_KEY)return {configured:false,message:'Wave prêt à connecter : ajoutez WAVE_API_KEY côté serveur.'};const rr=await fetch(`${process.env.WAVE_API_BASE_URL||'https://api.wave.com'}/v1/checkout/sessions`,{method:'POST',headers:{Authorization:`Bearer ${process.env.WAVE_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({amount:String(o.total),currency:'XOF',client_reference:o.id,success_url:`${BASE}/?payment=success&order=${o.id}`,error_url:`${BASE}/?payment=error&order=${o.id}`})});const j=await rr.json();if(!rr.ok)throw Error(`Wave checkout error ${rr.status}`);return j}
function dashboard(d){const paid=d.orders.filter(o=>o.payment_status==='PAID');return{orders:d.orders.length,revenue:paid.reduce((s,o)=>s+o.total,0),paid:paid.length,toDeliver:d.orders.filter(o=>o.fulfillment_status!=='DELIVERED'&&o.payment_status!=='CANCELLED').length,lowStock:d.products.filter(p=>p.stock<=2).length}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,BASE), d=load();if(req.method==='GET'&&u.pathname==='/health')return send(res,200,{ok:true,service:'Maison Micky V2'});if(req.method==='GET'&&u.pathname==='/api/products')return send(res,200,d.products);if(req.method==='GET'&&u.pathname==='/api/orders')return send(res,200,d.orders);if(req.method==='GET'&&u.pathname==='/api/dashboard')return send(res,200,dashboard(d));
if(req.method==='POST'&&u.pathname==='/api/orders'){const b=await body(req);if(!b.customer?.name||!b.customer?.phone||!Array.isArray(b.items)||!b.items.length||!['wave','orange_money','cash'].includes(b.payment_method))throw Error('Commande invalide');let total=0;for(const i of b.items){const p=find(d,i.product_id);if(!p)throw Error('Produit inconnu');total+=p.price*i.qty}reserve(d,b.items);let c=d.customers.find(x=>x.phone===b.customer.phone);if(!c){c={id:crypto.randomUUID(),...b.customer};d.customers.push(c)}const o={id:oid(),customer_id:c.id,customer:b.customer,items:b.items,total,payment_method:b.payment_method,payment_status:b.payment_method==='cash'?'COD_PENDING':'PENDING',fulfillment_status:'TO_PREPARE',stock_reserved:true,created_at:new Date().toISOString()};d.orders.unshift(o);save(d);let checkout=null;try{if(b.payment_method==='wave')checkout=await wave(o);if(b.payment_method==='orange_money')checkout={configured:false,message:'Orange Money prêt à connecter : ajoutez les identifiants/API marchand côté serveur.'}}catch(e){const dd=load(),oo=dd.orders.find(x=>x.id===o.id);oo.payment_status='PAYMENT_FAILED';restore(dd,oo);save(dd);throw e}return send(res,201,{order:o,checkout})}
let m=u.pathname.match(/^\/api\/orders\/([^/]+)$/);if(req.method==='PATCH'&&m){const o=d.orders.find(x=>x.id===m[1]);if(!o)return send(res,404,{error:'Commande introuvable'});const b=await body(req);for(const k of ['payment_status','fulfillment_status'])if(k in b)o[k]=b[k];if(['CANCELLED','PAYMENT_FAILED'].includes(o.payment_status))restore(d,o);save(d);return send(res,200,o)}
if(req.method==='POST'&&u.pathname==='/webhooks/wave'){if(process.env.WAVE_WEBHOOK_SECRET && req.headers['wave-signature']!==process.env.WAVE_WEBHOOK_SECRET)return send(res,401,{error:'Signature webhook invalide'});const e=await body(req);if(e.id&&d.events.includes(e.id))return send(res,200,{ok:true});if(e.id)d.events.push(e.id);const x=e.data||{},o=d.orders.find(v=>v.id===x.client_reference);if(o){if(e.type==='checkout.session.completed'&&x.payment_status==='succeeded'){o.payment_status='PAID';o.paid_at=x.when_completed||new Date().toISOString()}if(e.type==='checkout.session.payment_failed'){o.payment_status='PAYMENT_FAILED';restore(d,o)}}save(d);return send(res,200,{ok:true})}
if(req.method==='GET'){let f=u.pathname==='/'?'index.html':u.pathname.slice(1);f=path.normalize(f).replace(/^\.\.(\/|\\|$)/,'');const fp=path.join(PUB,f);if(fp.startsWith(PUB)&&fs.existsSync(fp)){const ext=path.extname(fp),type=ext==='.html'?'text/html; charset=utf-8':ext==='.css'?'text/css':'application/octet-stream';return send(res,200,fs.readFileSync(fp),type)}}return send(res,404,{error:'Introuvable'})}catch(e){return send(res,400,{error:e.message})}});server.listen(PORT,()=>console.log(`Maison Micky V2: ${BASE}`));
